// Copyright (C) Tenacom and contributors. Licensed under the MIT license.
// See LICENSE file in the project root for full license information.

#nullable enable

/// <summary>
/// Provides shortcut methods for .NET SDK operations.
/// </summary>
sealed class DotNetService
{
    private readonly ICakeContext _context;
    private readonly OptionsService _options;
    private readonly ServerAdapter _server;
    private readonly PathsService _paths;
    private readonly VersionService _version;
    private readonly DotNetMSBuildSettings _msBuildSettings;

    /// <summary>
    /// Initializes a new instance of the <see cref="DotNetService"/> class.
    /// </summary>
    /// <param name="context">The _context context.</param>
    public DotNetService(ICakeContext context, OptionsService options, ServerAdapter server, PathsService paths, VersionService version)
    {
        Guard.IsNotNull(context);
        Guard.IsNotNull(options);
        Guard.IsNotNull(server);
        Guard.IsNotNull(paths);
        Guard.IsNotNull(version);
        _context = context;
        _options = options;
        _server = server;
        _paths = paths;
        _version = version;
        _msBuildSettings = new DotNetMSBuildSettings {
            MaxCpuCount = 1,
            ContinuousIntegrationBuild = server.IsCloudBuild,
            NoLogo = true,
        };
        SolutionPath = context.GetFiles("*.sln").FirstOrDefault() ?? context.Fail<FilePath>(255, "Cannot find a solution file.");
        Solution = context.ParseSolution(SolutionPath);
        Configuration = context.Argument("configuration", "Release");
        ArtifactsPath = paths.AllArtifacts.Combine(Configuration);
    }

    /// <summary>
    /// Gets the path of the solution file.
    /// </summary>
    public FilePath SolutionPath { get; }

    /// <summary>
    /// Gets the parsed solution.
    /// </summary>
    public SolutionParserResult Solution { get; }

    /// <summary>
    /// Gets the configuration to build.
    /// </summary>
    public string Configuration { get; }

    /// <summary>
    /// Gets the path of the directory where build artifacts for <see cref="Configuration"> are stored.
    /// </summary>
    public DirectoryPath ArtifactsPath { get; }

    /// <summary>
    /// Restores all NuGet packages for the solution.
    /// </summary>
    public void RestoreSolution()
    {
        _context.Information("Restoring NuGet packages for solution...");
        _context.DotNetRestore(SolutionPath.FullPath, new() {
            MSBuildSettings = _msBuildSettings,
            DisableParallel = true,
            Interactive = false,
        });
    }

    /// <summary>
    /// Build all projects in the solution.
    /// </summary>
    /// <param name="restore"><see langword="true"/> to restore NuGet packages before building, <see langword="false"/> otherwise.</param>
    public void BuildSolution(bool restore)
    {
        _context.Information($"Building solution (restore = {restore})...");
        _context.DotNetBuild(SolutionPath.FullPath, new() {
            Configuration = Configuration,
            MSBuildSettings = _msBuildSettings,
            NoLogo = true,
            NoRestore = !restore,
        });
    }

    /// <summary>
    /// Run all tests for the solution.
    /// </summary>
    /// <param name="restore"><see langword="true"/> to restore NuGet packages before testing, <see langword="false"/> otherwise.</param>
    /// <param name="build"><see langword="true"/> to build the solution before testing, <see langword="false"/> otherwise.</param>
    /// <param name="collect"><see langword="true"/> to collect coverage data with Coverlet, <see langword="false"/> otherwise.</param>
    /// <remarks>
    /// <para>If successful, this method will merge all coverage reports generated by VSTest into a single file suitable for upload to Codecov.</para>
    /// <para>To merge coverage reports, this methods requires the <c>dotnet-reportgenerator-globaltool</c> .NET CLI tool to be installed.</para>
    /// </remarks>
    public void TestSolution(bool restore, bool build, bool collect)
    {
        _context.Information($"Running tests (restore = {restore}, build = {build}, collect = {collect})...");
        _context.DotNetTest(SolutionPath.FullPath, new() {
            Configuration = Configuration,
            MSBuildSettings = _msBuildSettings,
            NoBuild = !build,
            NoLogo = true,
            NoRestore = !restore,
            ArgumentCustomization = args => collect
                ? args.Append("--collect:\"XPlat Code Coverage\"")
                : args,
        });

        // Merge coverage reports only if there are any
        if (collect)
        {
            var reports = string.Join(';', GetCodeCoverageReportPaths());
            if (string.IsNullOrEmpty(reports))
            {
                _context.Information("No coverage reports were generated.");
            }
            else
            {
                _context.Information("Merging coverage reports...");
                _context.DotNetTool($"reportgenerator \"-reports:{reports}\" \"-targetDir:{_paths.Temp.ToString()}\" -reporttypes:Cobertura");
            }
        }
    }

    /// <summary>
    /// Run the Pack target on the solution. This usually produces NuGet packages, but Buildvana SDK may hijack the target to produce, for example, setup executables.
    /// </summary>
    /// <param name="restore"><see langword="true"/> to restore NuGet packages before packing, <see langword="false"/> otherwise.</param>
    /// <param name="build"><see langword="true"/> to build the solution before packing, <see langword="false"/> otherwise.</param>
    public void PackSolution(bool restore, bool build)
    {
        _context.Information($"Packing solution (restore = {restore}, build = {build})...");
        _context.DotNetPack(SolutionPath.FullPath, new() {
            Configuration = Configuration,
            MSBuildSettings = _msBuildSettings,
            NoBuild = !build,
            NoLogo = true,
            NoRestore = !restore,
        });
    }

    /// <summary>
    /// Asynchronously pushes all produced NuGet packages to the appropriate NuGet server.
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the ongoing operation.</returns>
    public async Task NuGetPushAllAsync()
    {
        const string nupkgMask = "*.nupkg";
        if (!SysDirectory.EnumerateFiles(ArtifactsPath.FullPath, nupkgMask).Any())
        {
            _context.Verbose("No .nupkg files to push.");
            return;
        }

        var isPrivate = await _server.IsPrivateRepositoryAsync().ConfigureAwait(false);
        var nugetSource = _options.GetOptionOrFail<string>(isPrivate ? "privateNugetSource" : _version.IsPrerelease ? "prereleaseNugetSource" : "releaseNugetSource");
        var nugetApiKey = _options.GetOptionOrFail<string>(isPrivate ? "privateNugetKey" : _version.IsPrerelease ? "prereleaseNugetKey" : "releaseNugetKey");
        var nugetPushSettings = new DotNetNuGetPushSettings
        {
            ForceEnglishOutput = true,
            Source = nugetSource,
            ApiKey = nugetApiKey,
            SkipDuplicate = true,
        };

        var packages = SysPath.Combine(ArtifactsPath.FullPath, nupkgMask);
        foreach (var path in _context.GetFiles(packages))
        {
            _context.Information($"Pushing {path} to {nugetSource}...");
            _context.DotNetNuGetPush(path, nugetPushSettings);
        }
    }

    private IEnumerable<string> GetCodeCoverageReportPaths()
    {
        foreach (var testResultsDirectory in Solution.Projects.Select(static x => x.Path.GetDirectory().Combine("TestResults")))
        {
            if (!_context.DirectoryExists(testResultsDirectory))
            {
                continue;
            }

            var globPattern = new GlobPattern(string.Join(testResultsDirectory.Separator, testResultsDirectory.FullPath, "**", "coverage.cobertura.xml"));
            foreach (var path in _context.GetFiles(globPattern))
            {
                yield return _context.Environment.WorkingDirectory.GetRelativePath(path).ToString();
            }
        }
    }
}
